export { default as Home } from './Home';
export { default as Packet } from './Packet/Packet';
export { default as Recharge } from './Pay/Recharge';
export { default as BindUser } from './User/BindUser';
export { default as User } from './User/User';
export { default as History } from './Pay/History';
export { default as Result } from './Pay/Result';
export { default as BindResult } from './User/BindResult';
export { default as Chat } from './Chat';