export const RECEIVE_BASIC_INFO = 'RECEIVE_BASIC_INFO';
export type RECEIVE_BASIC_INFO = typeof RECEIVE_BASIC_INFO;

export const RECEIVE_WECHAT_PERSONAL_INFO = 'RECEIVE_WECHAT_PERSONAL_INFO';
export type RECEIVE_WECHAT_PERSONAL_INFO = typeof RECEIVE_WECHAT_PERSONAL_INFO;

export const RECEIVE_WECHAT_RECORDS = 'RECEIVE_WECHAT_RECORDS';
export type RECEIVE_WECHAT_RECORDS = typeof RECEIVE_WECHAT_RECORDS;

export const RECEIVE_WECHAT_BALANCE = 'RECEIVE_WECHAT_BALANCE';
export type RECEIVE_WECHAT_BALANCE = typeof RECEIVE_WECHAT_BALANCE;

export const RECEIVE_BONUS_DETAIL = 'RECEIVE_BONUS_DETAIL';
export type RECEIVE_BONUS_DETAIL = typeof RECEIVE_BONUS_DETAIL;

export const RECEIVE_CURRENT_IMAGE = 'RECEIVE_CURRENT_IMAGE';
export type RECEIVE_CURRENT_IMAGE = typeof RECEIVE_CURRENT_IMAGE;