export const RECEIVE_BASIC_INFO = 'RECEIVE_BASIC_INFO';
export type RECEIVE_BASIC_INFO = typeof RECEIVE_BASIC_INFO;

export const RECEIVE_WECHAT_PERSONAL_INFO = 'RECEIVE_WECHAT_PERSONAL_INFO';
export type RECEIVE_WECHAT_PERSONAL_INFO = typeof RECEIVE_WECHAT_PERSONAL_INFO;

export const RECEIVE_WECHAT_RECORDS = 'RECEIVE_WECHAT_RECORDS';
export type RECEIVE_WECHAT_RECORDS = typeof RECEIVE_WECHAT_RECORDS;

export const RECEIVE_WECHAT_BALANCE = 'RECEIVE_WECHAT_BALANCE';
export type RECEIVE_WECHAT_BALANCE = typeof RECEIVE_WECHAT_BALANCE;